### PR TITLE
Add file handler only once to each OdpsLogger

### LINKED ISSUE #84: [BUG]日志重复打印，每创建一次连接多打印一次日志
**Describe the bug**
日志重复打印，每创建一次连接多打印一次日志
OdpsDriver. connect(url, info);方法中调用new OdpsConnection(url, info) ；
每次都会实例化一个log
    log = new OdpsLogger(getClass().getName(), null, logConfFile, false, connRes.isEnableOdpsLogger());
在OdpsLogger中
odpsLogger= Logger.getLogger(name);
每次实例会追加一个fileHanlder到odpsLogger;  
odpsLogger.addHandler(fileHandler);
导致创建一万次连接后，一条日志会在jdbc.log中打印一万遍

### PR DESCRIPTION
**Pull request by cornmonster**
## What do these changes do?

Fix #84 

## Related issue number

#84

### CODE REVIEW

**Comment by lyman** [comment]
Since new implementation is to assign new logger to each connection, it is better to show connection id in log text.

Also, it is better to replace connection id from 24 bytes uuid to a self-increase integer.

**Comment by sanluan** [comment]
并没有解决日志重复打印的bug

**Comment by cornmonster** [comment]
> 并没有解决日志重复打印的bug

如果发现还有问题的话，贴下验证代码和日志吧

**Comment by sanluan** [comment]
日志重复打印，每创建一次连接多打印一次日志
OdpsDriver. connect(url, info);方法中调用new OdpsConnection(url, info) ；
每次都会实例化一个log
log = new OdpsLogger(getClass().getName(), null, logConfFile, false, connRes.isEnableOdpsLogger());
在OdpsLogger中
odpsLogger= Logger.getLogger(name);
每次实例会追加一个fileHanlder到odpsLogger;
odpsLogger.addHandler(fileHandler);
导致创建一万次连接后，一条日志会在jdbc.log中打印一万遍

**Pull request merged**
